// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhD6FyAi2ALwwq8pxpT2Hh41VqHkwnXYA',
    appId: '1:929864622331:web:3c1147a3cb7d30711e905e',
    messagingSenderId: '929864622331',
    projectId: 'washpoint-f2e9b',
    authDomain: 'washpoint-f2e9b.firebaseapp.com',
    storageBucket: 'washpoint-f2e9b.firebasestorage.app',
    measurementId: 'G-442GSFWB9R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB85IgflWGnUgcfde_rb0TiINKjzYzxiNA',
    appId: '1:929864622331:android:3942ea32a1f251371e905e',
    messagingSenderId: '929864622331',
    projectId: 'washpoint-f2e9b',
    storageBucket: 'washpoint-f2e9b.firebasestorage.app',
  );
}
